### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by antho6222** [sonia-auv/octopus-telemetry#10]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Context
Implémenter la toolbar avec les composants suivant:
- Mission et kill switch.
- Activation des moteurs.
- Démarrage des caméras.
- Batteries.

**Comment by laurentboisvert** [comment]
Closing this - merged in https://github.com/sonia-auv/octopus-telemetry/pull/46
